const HELLO_WORLD = "HELLO_WORLD";
const CHANGE_NAME = "CHANGE_NAME";

const START_GET_DATA_NEWS = "START_GET_DATA_NEWS";
const SUCCESS_GET_DATA_NEWS = "SUCCESS_GET_DATA_NEWS";
const FAIL_GET_DATA_NEWS = "FAIL_GET_DATA_NEWS";

export default {
  HELLO_WORLD,
  CHANGE_NAME,
  START_GET_DATA_NEWS,
  SUCCESS_GET_DATA_NEWS,
  FAIL_GET_DATA_NEWS,
};
